include $(GOROOT)/src/Make.inc

TARG=bugnuts/state
GOFILES=\
	metrics.go\
	montecarlo.go\
	movement.go\
	process.go\
	query.go\
	state.go\
	statistics.go\
	targets.go\

include $(GOROOT)/src/Make.pkg
