include $(GOROOT)/src/Make.inc

TARG=bugnuts/combat
GOFILES=\
	arena.go\
	combat.go\
	monte.go\
	moves.go\
	moverisk.go\
	partition.go\
	playermask.go\
	score.go\
	threat.go\



include $(GOROOT)/src/Make.pkg
